apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor-ingress-gateway
spec:
  rules:
  - host: local.horbor.dev
    http:
      paths:
      - backend:
          serviceName: harbor
          servicePort: 8080