apiVersion: v1
kind: Pod
metadata:
  labels:
    app: API
  name: locomoco-dance-pod
  namespace: local-mobile
spec:
  containers:
  - name: locomoco-dance-container
    image: local.harbor.dev:80/mobile/locomoco-dance:latest
